import { Community } from '@/types';

export const fallbackCommunities: Record<string, Community> = {
  'catedral-matriz': {
    id: 'c0000000-0000-0000-0000-000000000001',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Catedral Sagrado Coração de Jesus (Matriz)',
    slug: 'catedral-matriz',
    patron_saint: 'Sagrado Coração de Jesus',
    is_headquarters: true,
    address: 'Praça Frei José, Nº 26',
    neighborhood: 'Centro',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1927',
    feast_day: 'Solenidade do Sagrado Coração de Jesus (Junho)',
    history: 'Criada em 24 de dezembro de 1927 pelo primeiro bispo do Espírito Santo, Dom Fernando de Souza Monteiro, a Igreja Matriz tornou-se o coração pastoral do Vale do Rio Doce. Em 1990, foi elevada à dignidade de Catedral com a criação da Diocese de Colatina.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'perpetuo-socorro': {
    id: 'c0000000-0000-0000-0000-000000000002',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Nossa Senhora do Perpétuo Socorro',
    slug: 'perpetuo-socorro',
    patron_saint: 'Nossa Senhora do Perpétuo Socorro',
    is_headquarters: false,
    address: 'Rua Lígia Fagundes Guerra, Nº 05',
    neighborhood: 'Bairro Perpétuo Socorro',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1956',
    feast_day: '27 de Junho',
    history: 'Uma das primeiras comunidades da expansão urbana de Colatina, erguida com a dedicação fervorosa das famílias pioneiras e com grande devoção mariana.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'sagrada-familia': {
    id: 'c0000000-0000-0000-0000-000000000003',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Sagrada Família',
    slug: 'sagrada-familia',
    patron_saint: 'Sagrada Família',
    is_headquarters: false,
    address: 'Rua Francisco Cunha, S/N',
    neighborhood: 'Bairro Maria Ismênia',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1968',
    feast_day: 'Domingo no Oitavário do Natal',
    history: 'Comunidade acolhedora no Bairro Maria Ismênia, polo das Pastorais Familiares e círculos bíblicos que reúnem as famílias das redondezas.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'sao-francisco-de-assis': {
    id: 'c0000000-0000-0000-0000-000000000004',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade São Francisco de Assis',
    slug: 'sao-francisco-de-assis',
    patron_saint: 'São Francisco de Assis',
    is_headquarters: false,
    address: 'Rua Fabiano Silvas, S/N',
    neighborhood: 'Bairro Operário',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1974',
    feast_day: '04 de Outubro',
    history: 'Nascida do trabalho operário e da espiritualidade franciscana de fraternidade, simplicidade evangélica e cuidado com a criação.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'sao-pedro': {
    id: 'c0000000-0000-0000-0000-000000000005',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade São Pedro',
    slug: 'sao-pedro',
    patron_saint: 'São Pedro Apóstolo',
    is_headquarters: false,
    address: 'Av. Pedro Vitalli, S/N',
    neighborhood: 'Bairro Tropical',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1981',
    feast_day: '29 de Junho',
    history: 'Erguida no Bairro Tropical, destaca-se pelo espírito missionário e pelas celebrações vivas da Palavra de Deus em profunda união com a Paróquia.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'nossa-senhora-de-guadalupe': {
    id: 'c0000000-0000-0000-0000-000000000006',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Nossa Senhora de Guadalupe',
    slug: 'nossa-senhora-de-guadalupe',
    patron_saint: 'Nossa Senhora de Guadalupe',
    is_headquarters: false,
    address: 'Rua Matilde Guerra Comério, S/N',
    neighborhood: 'Vista da Serra',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1989',
    feast_day: '12 de Dezembro',
    history: 'No Bairro Vista da Serra, possui como padroeira a Mãe das Américas. É marcada por juventude expressiva e grande fervor nas novenas de dezembro.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'santa-luzia': {
    id: 'c0000000-0000-0000-0000-000000000007',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Santa Luzia',
    slug: 'santa-luzia',
    patron_saint: 'Santa Luzia',
    is_headquarters: false,
    address: 'Rua João da Mata, S/N',
    neighborhood: 'Bairro Alto Vila Nova',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1979',
    feast_day: '13 de Dezembro',
    history: 'No alto do Bairro Alto Vila Nova, a capela de Santa Luzia é ponto de peregrinação e bênção dos olhos para centenas de devotos durante sua festa anual.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'nossa-senhora-da-penha': {
    id: 'c0000000-0000-0000-0000-000000000008',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Nossa Senhora da Penha',
    slug: 'nossa-senhora-da-penha',
    patron_saint: 'Nossa Senhora da Penha',
    is_headquarters: false,
    address: 'Rua Macanã, Nº 63',
    neighborhood: 'Bairro Moacir Brotas',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1962',
    feast_day: 'Oitava da Páscoa (Segunda-feira)',
    history: 'No Bairro Moacir Brotas, homenageia com devoção a padroeira capixaba, cultivando com amor a caridade cristã e as tradições de fé.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'santo-expedito': {
    id: 'c0000000-0000-0000-0000-000000000009',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade Santo Expedito',
    slug: 'santo-expedito',
    patron_saint: 'Santo Expedito',
    is_headquarters: false,
    address: 'Praça Vitória Régia, S/N',
    neighborhood: 'Bairro Jardim Planalto',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '1995',
    feast_day: '19 de Abril',
    history: 'Na Praça Vitória Régia do Jardim Planalto, a comunidade atrai fiéis nas causas justas e urgentes, mantendo acolhimento e assistência fraterna.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'sao-bento': {
    id: 'c0000000-0000-0000-0000-000000000010',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade São Bento',
    slug: 'sao-bento',
    patron_saint: 'São Bento',
    is_headquarters: false,
    address: 'Rua Floriano Alves Brandão, S/N',
    neighborhood: 'Bairro Residencial Nobre',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '2004',
    feast_day: '11 de Julho',
    history: 'No Residencial Nobre, vive o lema beneditino da oração e do trabalho honesto, promovendo a evangelização e a acolhida pastoral.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'sao-lucas': {
    id: 'c0000000-0000-0000-0000-000000000011',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Comunidade São Lucas',
    slug: 'sao-lucas',
    patron_saint: 'São Lucas Evangelista',
    is_headquarters: false,
    address: 'Av. dos Imigrantes, S/N',
    neighborhood: 'Bairro Noêmia Vitalli',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '2008',
    feast_day: '18 de Outubro',
    history: 'Tem como padroeiro o evangelista da misericórdia, destacando-se pela Pastoral da Saúde, visita aos enfermos e acolhida a todas as famílias.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  'santa-rita-brisa-do-vale': {
    id: 'c0000000-0000-0000-0000-000000000022',
    parish_id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Grupo de Reflexão Santa Rita',
    slug: 'santa-rita-brisa-do-vale',
    patron_saint: 'Santa Rita de Cássia',
    is_headquarters: false,
    address: 'Bairro Brisa do Vale',
    neighborhood: 'Brisa do Vale',
    city: 'Colatina',
    state: 'ES',
    foundation_year: '2018',
    feast_day: '22 de Maio',
    history: 'Núcleo vivo de oração e partilha da Palavra de Deus reunido no Bairro Brisa do Vale. Sob a poderosa intercessão de Santa Rita de Cássia, as famílias do bairro se reúnem semanalmente em círculos bíblicos de reflexão, terço e fraternidade cristã em profunda união com a Catedral.',
    is_active: true,
    created_at: new Date().toISOString(),
  },
};

export const fallbackCommunitiesList: Community[] = Object.values(fallbackCommunities);

export function getCommunitySlug(c: Community): string {
  if (c.slug) return c.slug;
  if (c.is_headquarters) return 'catedral-matriz';
  const name = c.name.toLowerCase();
  if (name.includes('perpétuo') || name.includes('perpetuo')) return 'perpetuo-socorro';
  if (name.includes('família') || name.includes('familia')) return 'sagrada-familia';
  if (name.includes('francisco')) return 'sao-francisco-de-assis';
  if (name.includes('pedro')) return 'sao-pedro';
  if (name.includes('guadalupe')) return 'nossa-senhora-de-guadalupe';
  if (name.includes('luzia')) return 'santa-luzia';
  if (name.includes('penha')) return 'nossa-senhora-da-penha';
  if (name.includes('expedito')) return 'santo-expedito';
  if (name.includes('bento')) return 'sao-bento';
  if (name.includes('lucas')) return 'sao-lucas';
  if (name.includes('rita')) return 'santa-rita-brisa-do-vale';
  return 'catedral-matriz';
}
